---
- name: install httpd and start
  hosts: web-server
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
  - name: create tomcat user
    user:
      name: tomcat
  - name: create tomcat group
    group:
      name: tomcat
  - name: install java
    yum:
      name: java-1.8.0-openjdk
      state: present
   
